### ISSUE TITLE
Add message in button suggesting the pair does not exist yet to provide liquidity

### ISSUE THREAD

**Issue by therealpixelverse** [diffusion-fi/tokenlist#3]
When trying to add liquidity for a pair that does not yet exist, there is no clear message of what is happening:
![image](https://user-images.githubusercontent.com/93985697/151082137-71be9b87-8631-4006-a0ff-97d54ab71741.png)

The "Enter amount" button is blocked but it'd be great to show on the CTA the following: "Pair is not created yet" and gray it out like this:
![image](https://user-images.githubusercontent.com/93985697/151082717-c7e5c4d6-ee21-4edf-8568-556a6ff4de25.png)

**Comment by crypzoh** [comment]
https://github.com/diffusion-fi/interface/issues/15
