### ISSUE TITLE
Remove "Etherscan" everywhere

### ISSUE THREAD

**Issue by therealpixelverse** [diffusion-fi/tokenlist#5]
I think there is a bunch of places where Etherscan is hardcoded? Not sure but it pops up pretty much everywhere even with the evmos rpc config in metamask:
![image](https://user-images.githubusercontent.com/93985697/151083049-eb22859f-8953-42d3-9569-0a034e69f3ff.png)

**Comment by crypzoh** [comment]
Moved over: https://github.com/diffusion-fi/interface/issues/12
